name: "cauda"

env:
  NODE_ENV: "ci"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repo"
        uses: "actions/checkout@v4"
      
      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: 20
      
      - name: "Install the dependencies"
        run: "npm install"

      - name: "Test project"
        run: "node --test"
